spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:db}:${DB_PORT:5432}/${DB_NAME:chat_storage_prod}
    username: ${DB_USER:chat_user}
    password: ${DB_PASSWORD:chat_user}
    jpa:
      show-sql: false
      hibernate:
        ddl-auto: validate
      properties:
        hibernate:
          dialect: org.hibernate.dialect.PostgreSQLDialect
          default_schema: chat_storage_shema
    liquibase:
      enabled: true
      default_schema: chat_storage_shema

server:
  port: ${SERVER_PORT:8080}
  connection-timeout: 100000
  servlet:
    contextPath: /chat

security:
  app-secret-key: ${API_SECRET_KEY:prod-secure-key}